/*
 * ledDisplay.h
 *
 *  Created on: 30 paü 2022
 *      Author: KosmicznyBandyta
 */

#include "../configuration.h"
#include "common.h"

#ifndef HEADERS_LED_DISPLAY_H_
#define HEADERS_LED_DISPLAY_H_

// Macros for each segment
#define SHOW_SEGMENT_A (1 << P(PORT_FOR_ALL_SEGMENTS, SEGMENT_A))
#define SHOW_SEGMENT_B (1 << P(PORT_FOR_ALL_SEGMENTS, SEGMENT_B))
#define SHOW_SEGMENT_C (1 << P(PORT_FOR_ALL_SEGMENTS, SEGMENT_C))
#define SHOW_SEGMENT_D (1 << P(PORT_FOR_ALL_SEGMENTS, SEGMENT_D))
#define SHOW_SEGMENT_E (1 << P(PORT_FOR_ALL_SEGMENTS, SEGMENT_E))
#define SHOW_SEGMENT_F (1 << P(PORT_FOR_ALL_SEGMENTS, SEGMENT_F))
#define SHOW_SEGMENT_G (1 << P(PORT_FOR_ALL_SEGMENTS, SEGMENT_G))
#define SHOW_SEGMENT_H (1 << P(PORT_FOR_ALL_SEGMENTS, SEGMENT_H))

// Arabic numerlas
#define SHOW_COMMON_ZERO ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_C | SHOW_SEGMENT_D | SHOW_SEGMENT_E | SHOW_SEGMENT_F)
#define SHOW_COMMON_ONE ~(SHOW_SEGMENT_B | SHOW_SEGMENT_C)
#define SHOW_COMMON_TWO ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_D | SHOW_SEGMENT_E | SHOW_SEGMENT_G)
#define SHOW_COMMON_THREE ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_C | SHOW_SEGMENT_D | SHOW_SEGMENT_G)
#define SHOW_COMMON_FOUR ~(SHOW_SEGMENT_B | SHOW_SEGMENT_C | SHOW_SEGMENT_F | SHOW_SEGMENT_G)
#define SHOW_COMMON_FIVE ~(SHOW_SEGMENT_A | SHOW_SEGMENT_F | SHOW_SEGMENT_G | SHOW_SEGMENT_C | SHOW_SEGMENT_D)
#define SHOW_COMMON_SIX ~(SHOW_SEGMENT_A | SHOW_SEGMENT_F | SHOW_SEGMENT_E | SHOW_SEGMENT_D | SHOW_SEGMENT_C | SHOW_SEGMENT_G)
#define SHOW_COMMON_SEVEN ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_C)
#define SHOW_COMMON_EIGHT ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_C | SHOW_SEGMENT_D | SHOW_SEGMENT_E | SHOW_SEGMENT_F | SHOW_SEGMENT_G)
#define SHOW_COMMON_NINE ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_C | SHOW_SEGMENT_D | SHOW_SEGMENT_F | SHOW_SEGMENT_G)

// My fantasy
#define SHOW_ELF_ZERO ~(SHOW_SEGMENT_A | SHOW_SEGMENT_G)
#define SHOW_ELF_ONE ~(SHOW_SEGMENT_A | SHOW_SEGMENT_C | SHOW_SEGMENT_G)
#define SHOW_ELF_TWO ~(SHOW_SEGMENT_A | SHOW_SEGMENT_C | SHOW_SEGMENT_E | SHOW_SEGMENT_G)
#define SHOW_ELF_THREE ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_C | SHOW_SEGMENT_D | SHOW_SEGMENT_E)
#define SHOW_ELF_FOUR ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_C | SHOW_SEGMENT_G)
#define SHOW_ELF_FIVE ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_E | SHOW_SEGMENT_F | SHOW_SEGMENT_G)
#define SHOW_ELF_SIX ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_D | SHOW_SEGMENT_F | SHOW_SEGMENT_G)
#define SHOW_ELF_SEVEN ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B)
#define SHOW_ELF_EIGHT ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_D)
#define SHOW_ELF_NINE ~(SHOW_SEGMENT_A | SHOW_SEGMENT_B | SHOW_SEGMENT_D | SHOW_SEGMENT_G)

// Global variables
extern volatile uint8_t digit1;
extern volatile uint8_t digit2;
extern volatile uint8_t digit3;
extern volatile uint8_t digit4;
extern volatile uint8_t lang;

// Methos declarations
void init_led_display();
void dispose_led_display();
void display_number(uint16_t number);
uint16_t count_to_zero_in(uint16_t seconds);
uint16_t count_to_zero_continue(uint16_t number);

#endif /* HEADERS_LED_DISPLAY_H_ */
